export enum EColor {
	BLACK_WHITE = "BLACK_WHITE",
	BLACK_ORANGE = "BLACK_ORANGE",
	TRANSPARENT_ORANGE = "TRANSPARENT_ORANGE",
	TRANSPARENT_WHITE = "TRANSPARENT_WHITE",
	ORANGE_WHITE = "ORANGE_WHITE",
	RED_WHITE = "RED_WHITE",
	GREY_WHITE = "GREY_WHITE",
	WHITE_BLACK = "WHITE_BLACK",
	WHITE_RED = "WHITE_RED",
}
